# Generated by Django 5.1.6 on 2025-03-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="description",
            new_name="address",
        ),
    ]
