# Generated by Django 5.1.6 on 2025-05-17 07:11

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0002_rename_description_admission_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="academic_qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="courses_interested",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("MS-Office", "MS-Office"),
                    ("Hardware", "Hardware"),
                    ("Networking", "Networking"),
                    ("OS (Windows)", "OS (Windows)"),
                    ("OS (Linux)", "OS (Linux)"),
                    ("CCNA", "CCNA"),
                    ("MCSA", "MCSA"),
                    ("REDHAT", "REDHAT"),
                    ("Cloud (AWS)", "Cloud (AWS)"),
                    ("Cloud (Azure)", "Cloud (Azure)"),
                    ("Cyber Security", "Cyber Security"),
                    ("Ethical Hacking", "Ethical Hacking"),
                    ("Penetration Testing", "Penetration Testing"),
                    ("C & C ++ Programming", "C & C ++ Programming"),
                    ("Data Science", "Data Science"),
                    ("Data Analytics", "Data Analytics"),
                    ("AI / ML", "AI / ML"),
                    ("Python Programming", "Python Programming"),
                    ("JAVA", "JAVA"),
                    ("Mern-Stack", "Mern-Stack"),
                    ("Mean-Stack", "Mean-Stack"),
                    ("Web", "Web"),
                    ("JAVA Full Stack", "JAVA Full Stack"),
                ],
                max_length=270,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="enquiry_via",
            field=models.CharField(
                choices=[
                    ("Just Dial", "Just Dial"),
                    ("Social Media", "Social Media"),
                    ("Google", "Google"),
                    ("Referral", "Referral"),
                    ("Event / Workshop", "Event / Workshop"),
                ],
                default="Google",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="father_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Select", "Select"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                default="Select",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="known_languages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("English", "English"),
                    ("Hindi", "Hindi"),
                    ("Marathi", "Marathi"),
                ],
                max_length=21,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="mother_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
