# Generated by Django 5.2.1 on 2025-06-07 12:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_admission_academic_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='priority',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], default='Warm', max_length=10),
        ),
        migrations.AlterField(
            model_name='admission',
            name='courses_interested',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MS-Office', 'MS-Office'), ('Hardware', 'Hardware'), ('Networking', 'Networking'), ('OS (Windows)', 'OS (Windows)'), ('OS (Linux)', 'OS (Linux)'), ('CCNA', 'CCNA'), ('MCSA', 'MCSA'), ('REDHAT', 'REDHAT'), ('Cloud (AWS)', 'Cloud (AWS)'), ('Cloud (Azure)', 'Cloud (Azure)'), ('Cyber Security', 'Cyber Security'), ('Ethical Hacking', 'Ethical Hacking'), ('Penetration Testing', 'Penetration Testing'), ('C & C ++ Programming', 'C & C ++ Programming'), ('Data Science', 'Data Science'), ('Data Analytics', 'Data Analytics'), ('AI / ML', 'AI / ML'), ('Python Programming', 'Python Programming'), ('JAVA', 'JAVA'), ('Mern-Stack', 'Mern-Stack'), ('Mean-Stack', 'Mean-Stack'), ('Web', 'Web'), ('JAVA Full Stack', 'JAVA Full Stack')], default=[], max_length=270),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='known_languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], default=[], max_length=21),
            preserve_default=False,
        ),
    ]
