# Generated by Django 5.2.1 on 2025-06-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_admission_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='course_fee',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='priority',
            field=models.CharField(default='Warm', max_length=10),
        ),
    ]
