# Generated by Django 5.2.1 on 2025-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_admission_course_fee_alter_admission_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='course_fee',
        ),
        migrations.AddField(
            model_name='admission',
            name='facalty',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
    ]
