# Generated by Django 5.1.6 on 2025-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
