# Generated by Django 5.1.6 on 2025-03-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_converted_to_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="converted_to_client",
            new_name="converted_to_admission",
        ),
    ]
