# Generated by Django 5.1.6 on 2025-03-15 10:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_enquiry_via"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="courses_interested",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("MS-Office", "MS-Office"),
                    ("Hardware", "Hardware"),
                    ("Networking", "Networking"),
                    ("OS (Windows)", "OS (Windows)"),
                    ("OS (Linux)", "OS (Linux)"),
                    ("CCNA", "CCNA"),
                    ("MCSA", "MCSA"),
                    ("REDHAT", "REDHAT"),
                    ("Cloud (AWS)", "Cloud (AWS)"),
                    ("Cloud (Azure)", "Cloud (Azure)"),
                    ("Cyber Security", "Cyber Security"),
                    ("Penetration Testing", "Penetration Testing"),
                    ("C Programming", "C Programming"),
                    ("C ++ Programming", "C ++ Programming"),
                    ("Data Science", "Data Science"),
                    ("Data Analytics", "Data Analytics"),
                    ("AI / ML", "AI / ML"),
                    ("Python Programming", "Python Programming"),
                    ("JAVA", "JAVA"),
                    ("Mern-Stack", "Mern-Stack"),
                    ("Mean-Stack", "Mean-Stack"),
                    ("Web", "Web"),
                    ("JAVA Full Stack", "JAVA Full Stack"),
                ],
                max_length=264,
                null=True,
            ),
        ),
    ]
