# Generated by Django 5.1.6 on 2025-03-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_lead_courses_interested"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="description",
            new_name="address",
        ),
    ]
