# Generated by Django 5.1.6 on 2025-03-15 12:18

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_rename_description_lead_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="status",
        ),
        migrations.AddField(
            model_name="lead",
            name="father_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Not Available", "Not Available"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                default="Not Available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="mother_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="courses_interested",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("MS-Office", "MS-Office"),
                    ("Hardware", "Hardware"),
                    ("Networking", "Networking"),
                    ("OS (Windows)", "OS (Windows)"),
                    ("OS (Linux)", "OS (Linux)"),
                    ("CCNA", "CCNA"),
                    ("MCSA", "MCSA"),
                    ("REDHAT", "REDHAT"),
                    ("Cloud (AWS)", "Cloud (AWS)"),
                    ("Cloud (Azure)", "Cloud (Azure)"),
                    ("Cyber Security", "Cyber Security"),
                    ("Ethical Hacking", "Ethical Hacking"),
                    ("Penetration Testing", "Penetration Testing"),
                    ("C & C ++ Programming", "C & C ++ Programming"),
                    ("Data Science", "Data Science"),
                    ("Data Analytics", "Data Analytics"),
                    ("AI / ML", "AI / ML"),
                    ("Python Programming", "Python Programming"),
                    ("JAVA", "JAVA"),
                    ("Mern-Stack", "Mern-Stack"),
                    ("Mean-Stack", "Mean-Stack"),
                    ("Web", "Web"),
                    ("JAVA Full Stack", "JAVA Full Stack"),
                ],
                max_length=270,
                null=True,
            ),
        ),
    ]
