# Generated by Django 5.1.6 on 2025-03-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_remove_lead_status_lead_father_name_lead_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Select", "Select"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                default="Select",
                max_length=20,
            ),
        ),
    ]
