# Generated by Django 5.1.6 on 2025-03-15 13:06

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_alter_lead_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="academic_qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="known_languages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("English", "English"),
                    ("Hindi", "Hindi"),
                    ("Marathi", "Marathi"),
                ],
                max_length=21,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
