# Generated by Django 5.2.1 on 2025-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_academic_qualification_lead_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facalty',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
    ]
