# Generated by Django 5.2.1 on 2025-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_facalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='facalty',
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(default='', max_length=10),
        ),
    ]
