# Generated by Django 5.2.1 on 2025-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_remove_lead_facalty_alter_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facalty',
            field=models.CharField(default=[], max_length=10),
            preserve_default=False,
        ),
    ]
