# Generated by Django 5.2.1 on 2025-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_facalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='facalty',
            field=models.CharField(choices=[('Mrunal_Mam', 'Mrunal_Mam'), ('Ankita_Mam', 'Ankita_Mam'), ('Chaitany_Sir', 'Chaitany_Sir'), ('Dnyanda_Mam ', 'Dnyanda_Mam ')], default='SELECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='SELECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], default='Warm', max_length=100),
        ),
    ]
